spring.application.name=SpringBootApps

spring.datasource.url=jdbc:postgresql://dpg-d63v7rogjchc739c0mi0-a.virginia-postgres.render.com:5432/softwareengi_library_project?sslmode=require
spring.datasource.username=softwareengi_library_project_user
spring.datasource.password=UO2lITquWkLaQdAVOnSEVEphwAO9wmgz
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
server.port=8080

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true